#!/usr/bin/env python3
from pathlib import Path
import re,sys
root=Path(__file__).resolve().parents[1]
s=(root/'src'/'powerstream_api.cpp').read_text(encoding='utf-8')
base=(root/'tools'/'platformio_tls15z_memory_relief_ab.py').read_text(encoding='utf-8')
hard=(root/'tools'/'platformio_tls15z_ab7_hardening.py').read_text(encoding='utf-8')
ab8=(root/'tools'/'platformio_tls15z_ab8_hardware_fix.py').read_text(encoding='utf-8')
ini=(root/'platformio.ini').read_text(encoding='utf-8')
c=[]
def ck(n,x,d): c.append((n,bool(x),d))
ck('TLS verified','setCACert(ECOFLOW_CA_BUNDLE)' in s and 'setInsecure(' not in re.sub(r'//[^\n]*','',s),'CA verification retained')
ck('failed allocation telemetry','gTlsFailedAllocSize' in s and 'gTlsFailedInternalLargest' in s,'requested bytes and largest internal block observable')
ck('pre-GET attribution','gTlsInternalGetPreLargest' in s and 'gTlsInternalPreVerifyLargest' in s,'pre-handshake fragmentation observable')
ck('post-GET attribution','gTlsInternalGetPostLargest' in s and 'gTlsInternalPostVerifyLargest' in s,'post-handshake state observable')
# 15Z is generated by PlatformIO pre-scripts; do not require generated symbols to
# already exist in the checked-in C++ source. Verify the actual composition chain
# and the provenance/slot telemetry implemented by those generators.
chain=(ini.find('platformio_tls15z_memory_relief_ab.py'),ini.find('platformio_tls15z_ab7_hardening.py'),ini.find('platformio_tls15z_ab8_hardware_fix.py'))
ck('15Z generator chain', all(x>=0 for x in chain) and chain[0] < chain[1] < chain[2], 'base -> AB7 -> AB8 pre-script composition active')
ck('15Z generated provenance', all(x in base+hard+ab8 for x in ('tls15z_generation','tls15z_outcome','tls15z_stop_generation_before','tls15z_stop_generation_after','tls15z_slot_ready_pre_tls')), 'generated runtime exports generation/outcome/stop/slot evidence')
ck('15Z AB8 hardware fix','9.36.7.15Z-MEMORY-RELIEF-AB8' in ab8, 'AB8 hardware-fix generator retained')
ck('legacy preflight recorded','TLS_GET_MIN_LARGEST8 = 10240' in s,'old threshold recorded, not silently changed')
for n,o,d in c: print(f"{'PASS' if o else 'FAIL'} | {n} | {d}")
print(f"SUMMARY | pass={sum(x[1] for x in c)} fail={sum(not x[1] for x in c)} total={len(c)}")
sys.exit(0 if all(x[1] for x in c) else 1)
